# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a0503c93cdaf4a68cbd89b5c10e7d7d0986cf4367e81136441a01596f3f1109dcef2318de411d9bd353f7d48d77bcef4063fe60d29dc2c0e78ef81ee4f4a54

test:
  secret_key_base: a3bd4153898dfb90aefeb64190e0b1e216688619cbea18edc826f6e72f1be969364b9efbb09e143f778b2e24bb7f0e13734f8bdbc91eaed8024ffe81ba919fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
